

export const ARTICLE_GET_ALL_REQUEST = "ARTICLE_GET_ALL_REQUEST"
export const ARTICLE_GET_ALL_SUCCESS = "ARTICLE_GET_ALL_SUCCESS"
export const ARTICLE_GET_ALL_ERROR = "ARTICLE_GET_ALL_ERROR"


export const ARTICLE_POST_REQUEST = "ARTICLE_POST_REQUEST"
export const ARTICLE_POST_SUCCESS = "ARTICLE_POST_SUCCESS"
export const ARTICLE_POST_ERROR = "ARTICLE_POST_ERROR"

export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST"
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR"

export const AUTH_LOGOUT = "AUTH_LOGOUT"
