

export const ARTICLE_GET_ALL_REQUEST = "ARTICLE_GET_ALL_REQUEST"
export const ARTICLE_GET_ALL_SUCCESS = "ARTICLE_GET_ALL_SUCCESS"
export const ARTICLE_GET_ALL_ERROR = "ARTICLE_GET_ALL_ERROR"


export const ARTICLE_POST_REQUEST = "ARTICLE_POST_REQUEST"
export const ARTICLE_POST_SUCCESS = "ARTICLE_POST_SUCCESS"
export const ARTICLE_POST_ERROR = "ARTICLE_POST_ERROR"


export const ARTICLE_PUT_REQUEST = "ARTICLE_PUT_REQUEST"
export const ARTICLE_PUT_SUCCESS = "ARTICLE_PUT_SUCCESS"
export const ARTICLE_PUT_ERROR = "ARTICLE_PUT_ERROR"

export const ARTICLE_DELETE_REQUEST = "ARTICLE_DELETE_REQUEST"
export const ARTICLE_DELETE_SUCCESS = "ARTICLE_DELETE_SUCCESS"
export const ARTICLE_DELETE_ERROR = "ARTICLE_DELETE_ERROR"
